// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lotto_DB.lottoModel
{
    public partial class Menu
    {
        public int MenuId { get; set; }
        public string Icon { get; set; }
        public string Text { get; set; }
        public string To { get; set; }
    }
}