// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lotto_DB.lottoModel
{
    public partial class RoleMenu
    {
        public int RoleMenuId { get; set; }
        public int? RoleId { get; set; }
        public int? MenuId { get; set; }
        public DateTime? RoleMenuCreateDate { get; set; }
        public string RoleMenuCreateby { get; set; }
        public DateTime? RoleMenuUpdateDate { get; set; }
        public string RoleMenuUpdateby { get; set; }
    }
}