// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lotto_DB.lottoModel
{
    public partial class Role
    {
        public Role()
        {
            Account = new HashSet<Account>();
        }

        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public DateTime? RoleCreateDate { get; set; }
        public string RoleCreateby { get; set; }
        public DateTime? RoleUpdateDate { get; set; }
        public string RoleUpdateby { get; set; }

        public virtual ICollection<Account> Account { get; set; }
    }
}